server:
  port: 8081

spring:
  application:
    name: studp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studp?useSSL=false&serverTimezone=UTC
    username: root
    password: nigun1748hk
  redis:
    host: 192.168.70.128
    port: 6379
#    password: 123321
    url: redis://123321@192.168.70.128:6379
    lettuce:
      pool:  # redis连接池
        max-active: 10  # 最大连接
        max-idle: 10    # 最大空闲连接
        min-idle: 1     # 最小空闲连接
        time-between-eviction-runs: 10s  # 连接最长等待时间（超过则超时中断）
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.studp.entity # 别名扫描包
logging:
  level:
    com.studp.controller: info
    com.studp.service: debug
    com.studp.mapper: debug